### ISSUE TITLE
关于游戏关卡

### ISSUE THREAD

**Issue by Cosinhs** [tkoz0/bloxorz-solver#1]
游戏网址是这个吗，https://www.miniclip.com/games/bloxorz/en/#  

如果是的话json配置里好像有几个对不上，比如stage10的teleports应该是[1,12,1,9,1,12,0]而不是[1,12,1,9,1,12,1]。另外游戏里还有个winter关卡，有兴趣可以补上

**Comment by tkoz0** [comment]
The link to the game I used is: https://www.coolmathgames.com/0-bloxorz
The last number is only there so I was able to output a key press sequence to solve the Coolmath version.

**Comment by Cosinhs** [comment]
> The link to the game I used is: https://www.coolmathgames.com/0-bloxorz
> The last number is only there so I was able to output a key press sequence to solve the Coolmath version.

Thanks, got it
